platform :ios, '12.0'

target 'SocialSwap' do
  use_frameworks!
  # Pods for SocialSwap
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Analytics'
end
